export const ERROR_CODES = {
  INVALID_TOKEN: 'ERR_INVALID_TOKEN',
  MISSING_TOKEN: 'ERR_MISSING_TOKEN',
  MISSING_PLAYER_ID: 'ERR_MISSING_PLAYER_ID',
  ALREADY_CONNECTED: 'ERR_ALREADY_CONNECTED',
  INVALID_ROOM_ID: 'INVALID_ROOM_ID',
  ROOM_FULL_OR_NOT_FOUND: 'ROOM_FULL_OR_NOT_FOUND',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];


